name: CI Pipeline

on:
  push:
    branches:
      - CI_CD
  pull_request:
    branches:
      - CI_CD

jobs:

  tests:
    runs-on: ubuntu-latest
    needs: linting
    steps:
      - name: Check out the repository
        uses: actions/checkout@v2

      - name: Set up Python
        uses: actions/setup-python@v2
        with:
          python-version: '3.10'

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt

      - name: Run tests with coverage
        run: |
          pip install pytest coverage
          pytest --cov=my_project --cov-report=xml

  linting:
    runs-on: ubuntu-latest
    steps:
      - name: Check out the repository
        uses: actions/checkout@v3

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.10'

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt

      - name: Run Super Linter
        uses: github/super-linter@v4
        env:
          VALIDATE_PYTHON_RUFF: true
          FIX_PYTHON_BLACK: true
          FIX_PYTHON_ISORT: true
          FIX_PYTHON_PYINK: true
          FIX_PYTHON_RUFF: true
          DEFAULT_BRANCH: "CI_CD"
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          commit_user_name: super-linter

